<?php
/**
 * Copyright © Lesti, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

if($url = $block->getAjaxUrl()): ?>
    <script type="text/javascript">
        require(["jquery"],function($) {
            $(document).ready(function() {
                $.ajax({
                    url: <?php echo '"' . $url . '"'; ?>,
                    type: 'POST',
                    complete: function(response) {             
                        console.log(response);   
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });
            });
        });
    </script>
<?php endif;